### ISSUE TITLE
[Feature request] Creative Inv

### ISSUE THREAD

**Issue by BioTechproject27** [Sn0wix/Village-Pillage-Arise#2]
The creative inventory is a mess with the new blocks. Sorting the modded items with vanilla items (e.g. putting the Azalea boats next to the other boat types, etc) and perhaps making a seperate creative tab with the modded items would be nice.

**Comment by Sn0wix** [comment]
I don't want to create new tab, because i want the mod to feel as much vanila as possible, but i will look into sorting the items.

**Comment by BioTechproject27** [comment]
Fair enough ig
