### ISSUE TITLE
Battle Axes are not considered axes by the game

### ISSUE THREAD

**Issue by Fourmisain** [Sn0wix/Village-Pillage-Arise#4]
Battle Axes should extend from `AxeItem` and ideally also be part of the `"axes"` / `ItemTags.AXES` tag.

This allows for better mod compatibility, e.g. with [Axes Are Weapons](https://www.curseforge.com/minecraft/mc-mods/axes-are-weapons).
It also allows the Battle Axes to disable player shields and you can put damage enchants on them (via books).

It'll also allow stripping wood blocks, which you probably don't want, but that can easily be disabled by overriding `public ActionResult useOnBlock(ItemUsageContext context)` to just return `ActionResult.PASS`.

**Comment by Sn0wix** [comment]
Okay, i'll fix it. I'll also add the battle axes to the battle_axes tag under the c namespace.

**Comment by Fourmisain** [comment]
That was fast!
Thanks and happy early New Years!

**Comment by Sn0wix** [comment]
For you too :)
