### ISSUE TITLE
[ FABRIC 1.20.4 ] Silk Touch Should Only Drop Diamond Ore Block.

### ISSUE THREAD

**Issue by makumaku1974** [Sn0wix/Village-Pillage-Arise#5]
I find a bug or an intentional feature that it can dupe diamonds slowly with a pickaxe enchanted with Silk Touch. Meaning I still get Diamond Shards with a Silk Touch Pickaxe.

Every diamond ore drops a shard which is much more reasonable to use Fortune instead of Silk Touch.

**Comment by Sn0wix** [comment]
Thanks for reporting that. I don't want people to get infinite diamonds, so it's fixed now.

Btw it's not a shard but a crushed diamond.

**Comment by makumaku1974** [comment]
> Thanks for reporting that. I don't want people to get infinite diamonds, so it's fixed now.
> 
> Btw it's not a shard but a crushed diamond.

sherd
